/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-11-19 20:05:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.MemberDb;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

             MemberDb userData = (MemberDb)session.getAttribute("UserData");
             String user = (String)session.getAttribute("user");

      out.write("\r\n");
      out.write("<ul id=\"p7PMnav\">\r\n");
      out.write("  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/inventory.do\">Inventory</a></li>\r\n");
      out.write("  \r\n");
      out.write("  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/instructors.do\">QC</a></li>\r\n");
      out.write("  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/djs.do\">MSDS</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/music.do\">CofA</a></li>\r\n");
      out.write("\t\r\n");
      out.write("<!--\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/gallery/linksMain.jsp\">Links</a></li> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/market.do\">Invoices</a></li> \r\n");
      out.write("\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/media.do\">POs</a></li> \r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/struts/members/aboutMain.jsp\">Logout</a>\r\n");
      out.write("\t      <ul>\r\n");
      out.write("\t        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/struts/members/aboutMain.jsp\">About Membership</a></li>\r\n");
      out.write("\t\t\t\t\t");
 
             if (userData==null)
             { 
      out.write("\r\n");
      out.write("           <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/struts/login/loginMain.jsp\">Sign in</a></li>\r\n");
      out.write("              ");

              }
              else
              {
              
      out.write("\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login.do\">Sign out ");
      out.print(userData.getUsername() );
      out.write("</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/events.do?mode=myevents\">My Events </a></li>\r\n");
      out.write("\t\t\t ");

              if (userData.getAdmin()==1)
              { 
      out.write("\r\n");
      out.write("            \t  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/struts/admin/adminMain.jsp\">Admin</a></li>\r\n");
      out.write("              ");
 }
              } 
      out.write("\r\n");
      out.write("               \r\n");
      out.write("\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <!--[if lte IE 6]><style>#p7PMnav a{height:1em;}#p7PMnav li{height:1em;}#p7PMnav ul li{float:left;clear:both;width:100%}</style><![endif]-->\r\n");
      out.write("  <!--[if IE 6]><style>#p7PMnav ul li{clear:none;}</style><![endif]-->\r\n");
      out.write("  <!--[if IE 7]><style>#p7PMnav a{zoom:100%;}#p7PMnav ul li{float:left;clear:both;width:100%;}</style><![endif]-->\r\n");
      out.write("</ul>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
