/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-11-18 16:39:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class single_005fcol_005flayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/struts-tiles.tld", Long.valueOf(1360725336609L));
    _jspx_dependants.put("/p7pm/p7pmh0.css", Long.valueOf(1360725330805L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"  dir=\"ltr\">\r\n");
      out.write("<script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/p7pm/p7popmenu.js", out, true);
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=iso-8859-1\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\" media=\"screen\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/style.css", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<title>");
      if (_jspx_meth_tiles_005finsert_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\" media=\"screen\">\r\n");
      out.write("/* \n");
      out.write("  -----------------------------------\n");
      out.write("  PopMenu Magic Style Sheet\n");
      out.write("  by Project Seven Development\n");
      out.write("  www.projectseven.com\n");
      out.write("  Menu Type: Horizontal\n");
      out.write("  Style Theme:0 -Basic Style\n");
      out.write("  -----------------------------------\n");
      out.write("*/\n");
      out.write("#p7PMnav {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding:0;\n");
      out.write("}\n");
      out.write("#p7PMnav li {\n");
      out.write("\tlist-style-type: none;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("}\n");
      out.write("#p7PMnav ul {\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tbackground-color: #FFFFFF;\n");
      out.write("\tborder: 1px solid #000000;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tleft: -9000px;\n");
      out.write("\tz-index: 10000;\n");
      out.write("}\n");
      out.write("#p7PMnav a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tpadding: 4px 10px;\n");
      out.write("\tcolor: #666666;\n");
      out.write("\tline-height:1;\n");
      out.write("}\n");
      out.write("#p7PMnav a:hover, #p7PMnav a:active, #p7PMnav a:focus {\n");
      out.write("\tbackground-color: #5D2E26;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("\tletter-spacing: 0.01px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ------ the current page marker style ------ */\n");
      out.write("#p7PMnav .p7PMmark {\n");
      out.write("\tcolor: #333333;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("/* ------ the trigger link styles ------- */\n");
      out.write("\n");
      out.write("/*the trigger link */\n");
      out.write("#p7PMnav ul .p7PMtrg, #p7PMnav ul .p7PMon {\n");
      out.write("\tbackground-image:  url(img/p7PM_dark_east.gif);\n");
      out.write("\tbackground-repeat:\tno-repeat;\n");
      out.write("\tbackground-position: right center;\n");
      out.write("}\n");
      out.write("/* the active trigger link style */\n");
      out.write("#p7PMnav .p7PMon {\n");
      out.write("\tbackground-color: #5C2D23;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("}\n");
      out.write("/*the submenu classes */\n");
      out.write("\n");
      out.write("#p7PMnav .p7PMhide {\n");
      out.write("\tleft: -9000px;\n");
      out.write("}\n");
      out.write("#p7PMnav .p7PMshow {\n");
      out.write("\tleft: auto;\n");
      out.write("\tz-index: 20000 !important;\n");
      out.write("}\n");
      out.write("/* Top level menu width */\n");
      out.write("#p7PMnav li {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 124px;\n");
      out.write("}\n");
      out.write("#p7PMnav ul li {\n");
      out.write("\tfloat: none;\n");
      out.write("}\n");
      out.write("#p7PMnav ul, #p7PMnav ul li {\n");
      out.write("\twidth: 172px;\n");
      out.write("}\n");
      out.write("#pmmcrumb {\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tmargin-bottom: 16px;\n");
      out.write("\tcolor: #333333;\n");
      out.write("}\n");
      out.write("#pmmcrumb a, #pmmcrumb a:visited {\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\tcolor: #535FAC;\n");
      out.write("}\n");
      out.write("#pmmcrumb a:hover, #pmmcrumb a:active, #pmmcrumb a:focus {\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\tcolor: #333333;\n");
      out.write("}\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"P7_initPM(1,0,1,-20,10)\">\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/main_header.jpg\" alt=\"Setareh Biotech\" />\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu\">\r\n");
      out.write("      ");
      if (_jspx_meth_tiles_005finsert_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"clearer\"></div>\r\n");
      out.write("    <div class=\"main\" id=\"two-columns\">\r\n");
      out.write("     \t<div class=\"all\">\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\t    <div class=\"content\">\r\n");
      out.write("\t\t\t      \r\n");
      out.write("            ");
      if (_jspx_meth_tiles_005finsert_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("\t\t    <div class=\"clearer\"></div>\r\n");
      out.write("          <br /><br />\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  <div class=\"footer\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\t\t  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsert_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f0.setParent(null);
    // /layout/single_col_layout.jsp(15,7) name = attribute type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f0.setAttribute("title");
    int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
    if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsert_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f1 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f1.setParent(null);
    // /layout/single_col_layout.jsp(30,6) name = attribute type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f1.setAttribute("menu");
    int _jspx_eval_tiles_005finsert_005f1 = _jspx_th_tiles_005finsert_005f1.doStartTag();
    if (_jspx_th_tiles_005finsert_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsert_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.taglib.tiles.InsertTag _jspx_th_tiles_005finsert_005f2 = (org.apache.struts.taglib.tiles.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.get(org.apache.struts.taglib.tiles.InsertTag.class);
    _jspx_th_tiles_005finsert_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsert_005f2.setParent(null);
    // /layout/single_col_layout.jsp(38,12) name = attribute type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsert_005f2.setAttribute("body");
    int _jspx_eval_tiles_005finsert_005f2 = _jspx_th_tiles_005finsert_005f2.doStartTag();
    if (_jspx_th_tiles_005finsert_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f2);
    return false;
  }
}
