/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-11-18 16:39:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.inventory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.InventoryDb;
import db.MemberDb;
import model.Settings;
import java.util.Collection;
import java.util.Iterator;

public final class inventoryListBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"table_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<h1>Setareh Biotech Inventory</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<table id=\"mytable\" cellspacing=\"0\" summary=\"Setareh Inventory\">\r\n");
      out.write("<caption>Table 1: Setareh Inventory </caption>\r\n");
      out.write("\t<th scope=\"col\" abbr=\"Item\" class=\"nobg\">Item#</th>\r\n");
      out.write("  <th scope=\"col\" abbr=\"Product Name\">Product Name</th>\t\t\r\n");

MemberDb ud = (MemberDb)session.getAttribute("UserData");
if (ud==null) ud= new MemberDb();
int uid=0;
if (ud!=null)	uid=ud.getId();
Collection<InventoryDb> items = (Collection<InventoryDb>)request.getAttribute("InventoryList");
if (items==null) { out.println("no inventory found"); return; }
Iterator<InventoryDb> it = items.iterator();
InventoryDb idb=null;
while(it.hasNext())
{
  idb = it.next();
      out.write("\r\n");
      out.write("  <tr> \r\n");
      out.write("  \r\n");
      out.write("  <td valign=\"top\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/inventory.do?mode=showProduct&id=");
      out.print(idb.getId());
      out.write('"');
      out.write('>');
      out.print(idb.getItem_no());
      out.write("</a></td>\r\n");
      out.write("  <td valign=\"top\">");
      out.print(idb.getProduct_name());
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
