/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-11-20 17:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.inventory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import db.InventoryDb;
import db.MemberDb;
import model.Settings;
import java.util.Collection;
import java.util.Iterator;
import java.util.ArrayList;
import inventory.FileInfo;

public final class productBody_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"table_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"treeview.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<h1>Setareh Biotech Product</h1>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\"><tr><td valign=\"top\">\r\n");
      out.write("\r\n");
      out.write("<table id=\"mytable\" cellspacing=\"0\" summary=\"Setareh Product\">\r\n");
      out.write("<caption>Table 1: Setareh Product </caption>\r\n");

MemberDb ud = (MemberDb)session.getAttribute("UserData");
if (ud==null) ud= new MemberDb();
int uid=0;
if (ud!=null)	uid=ud.getId();
InventoryDb idb=(InventoryDb)request.getAttribute("Product"); 
ArrayList<FileInfo> fileDetails = (ArrayList<FileInfo>)request.getAttribute("FileDetails"); 
Iterator<FileInfo> it = fileDetails.iterator();

      out.write("\r\n");
      out.write(" <tr> \r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Item#</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.getItem_no());
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Name</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.getProduct_name());
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">CAS#</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.cas_no);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">MDL#</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.mdl_no);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Molecular Wt</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.mol_wt);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Formula</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.formatFormula());
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Stock</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.stock());
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Unit Price</th>\r\n");
      out.write("   <td valign=\"top\">$ ");
      out.print(idb.unit_price);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Storage</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.storage);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Appearance</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.appearance);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Cost To Make</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.cost_to_make);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Invt Cost</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.invt_cost);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">PDT</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.pdt_line);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Analytical</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.analytical);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">Application</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.application);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("   <th scope=\"row\" class=\"spec\">References</th>\r\n");
      out.write("   <td valign=\"top\">");
      out.print(idb.refs);
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write("  </table>\r\n");
      out.write("  </td>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <td valign=\"top\">\r\n");
      out.write("  \r\n");
      out.write("  <table>\r\n");
      out.write("  <tr><td>\r\n");
      out.write("  <form name=\"myWebForm\" action=\"nothing\" method=\"post\">\r\n");
      out.write("   <input type=\"button\" value=\"QC\"/></td></tr>\r\n");
      out.write("   <tr><td>\r\n");
      out.write("    <tr><td> <input type=\"button\" value=\"MSDS\"/></td></tr>\r\n");
      out.write("  <tr><td> <input type=\"button\" value=\"Sales\" /></td></tr>\r\n");
      out.write("  <tr><td> <input type=\"button\" value=\"Vendors\"/></td></tr>\r\n");
      out.write("</form>\r\n");
      out.write("  </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("  <td>\r\n");
      out.write("  Documents<br><br>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"css-treeview\">\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        <li><input type=\"checkbox\" id=\"item-0\" /><label for=\"item-0\">QC</label>\r\n");
      out.write("           <ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final..</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt ...</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt Testing</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluoresce...</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-1\"  /><label for=\"item-1\">C of A</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final ..</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt ...</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt ..</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluorescence test</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-2\"  /><label for=\"item-2\">MSDS</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final Lot analysis</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt approval_reject</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt Testing</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluorescence test</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-3\"  /><label for=\"item-3\">Labels</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Label lot ST 14047-1</a></li>\r\n");
      out.write("               <li><a href=\"./\">Label lot ST 14047-2</a></li>\r\n");
      out.write("               <li><a href=\"./\">Label lot ST 14047-3</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-4\"  /><label for=\"item-4\">Packing Slips</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final Lot analysis</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt approval_reject</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt Testing</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluorescence test</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-5\"  /><label for=\"item-5\">POs</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final Lot analysis</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt approval_reject</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt Testing</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluorescence test</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><input type=\"checkbox\" id=\"item-6\"  /><label for=\"item-6\">Invoices</label>\r\n");
      out.write("<ul>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC ABS test run</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Final Lot analysis</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt approval_reject</a></li>\r\n");
      out.write("               <li><a href=\"./\">Lot st 14047-1 QC Pdt Testing</a></li>\r\n");
      out.write("               <li><a href=\"./\">Template QC Fluorescence test</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("</li>\r\n");
      out.write("        \r\n");
      out.write("</li>\r\n");
      out.write(" \r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("  </td></tr></table>\r\n");
      out.write("  \r\n");
      out.write("\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
